# .github/workflows/deploy-prod.yml
name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --provenance=false --push \
            -t 861276103755.dkr.ecr.us-east-1.amazonaws.com/csgtest-app:prod-${{ github.sha }} ./app

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: terraform/environments/prod
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="image_url=861276103755.dkr.ecr.us-east-1.amazonaws.com/csgtest-app:prod-${{ github.sha }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}"